spring.application.name=base_student

spring.datasource.url=jdbc:postgresql://localhost:5432/base_student
spring.datasource.username=susanagallegos
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
